### ISSUE TITLE
latexcgi in your own server

### ISSUE THREAD

**Issue by cpierquet** [davidcarlisle/latexcgi#1]
Hi, tks for the job, nice feature ;-)

Is it possible to install the features (script js and/or latexcgi) in a private server, with a local installation of texlive (in orider to test with own packages and classes for examples) ?

**Comment by davidcarlisle** [comment]
You can host a page with the frontend editing interface on a local server or even just in your local filesysem, eg copy

https://davidcarlisle.github.io/latexcgi/test.html

locally and you can edit that with whatever tex document you wish.

If you want to host the tex server itself that is possible (it is all open source MIT licenced) but currently not really documented, basically take the above example change the reference to the javascript to point to a copy and change the javascript to change the POST URI from texlive.net to a URI on your server and then you just need to arrange that latexcgi perl script is accessible via cgi bin on your server and that a texlive installation is in the path of the account running apache.  

I have some notes taken as I moved the server from https://latexcgi.xyz to https://texlive.net but they are not suitable for public use at present (contain passwords and other private details) I may at some point convert these to a public installation documentation for the server but I can not promise this will happen.

**Comment by cpierquet** [comment]
Tks, it's working with little changes in the js and cgi scripts !
Now I'd like to compile a tex file with python code, so pdflatex + pythontex + pdflatex, it's possible ?

**Comment by davidcarlisle** [comment]
yes basically things are locked down just to things I need, have a look  at how context is allowed (that was a local addition on the server but I just pushed it here 5cf8daf  so if you could for example allow `xpythontex` as an engine here and and `% !TEX xpythontex` in the magic comments in the runlatex.js Javascript then you just need to make a script available on the serever xpythontex that does pdflatex;pythontex;pdflatex 

actually easiest just to test things is steal a command you don't plan to use that is otherwise allowed say `pdflatex-dev` and at the back end make a pdflatex-dev script that is ahead of the texlive pdflatex-dev that runs your pythontex pipeline. If that works you have all the dependencies set up then allowing a "new" engine name is just a few obvious changes here and there.

**Comment by cpierquet** [comment]
Ok, it's not easy for me... but I'll try to understand how to allow new engines like latex (for pstricks code !) and xpythontex !

**Comment by davidcarlisle** [comment]
OK as you have it running in your server, I think I'll close this. Feel free to open new feature request issues for adding new engines. (although if you got this far adding one should be easy: when I added context the other day it was only a matter of changing the regular expressions in runlatex.js and latexcgi that restrict the engine names)

But I can't promise when or if I would handle such a feature, this is a spare time 1-man project and has no support and no warranty for users.  Certainly I am unlikely to allow pythontex on the public server as I think that would allow anyone to run arbitrary python code  not constrained by the tex shell-escape features, but there is no reason not to allow it on your private server version.

**Comment by davidcarlisle** [comment]
@cpierquet  as of a few minutes ago the runlatex-sk script allows latex as well as pdflaetx (added one `?` :-) and this is allowed at the back end, see todays update to the latexcgi script to call ps2pdf, you can see pstricks running at

https://davidcarlisle.github.io/latexcgi/test-sk#latex
